apiVersion : apps/v1
kind : Deployment
metadata :
  name : javawebapp
  labels :
    app : javawebapp
    tier : frontend
spec:
  replicas : 2
  selector :
    matchLabels:
      app : javawebapp
      tier : frontend
  template :
    metadata :
      labels :
        app : javawebapp
        tier : frontend    
    spec :
      containers :
      - name : javawebapp-container
        image : mamathasama/javawebapp:latest
        ports :
        - containerPort : 8080
